travis:
  secure:
    BINSTAR_TOKEN: AWiZeoWd5KK0TJy2toIesCNuAG+wvU+efqOHq1Ur05hzZtFp4DgalEZauZs2alydiOTQExtOxvY5WmutjMCTNHRmbkdU0xU8leUODs4iVMrkNIBNQmp1mF+GJnO9+6O5vDl6fUWgItawll6hiBy+0dN6CJ3O1iK2KdObQ59PQL6hsUbd8x3ofLJ/JTikHGtyFYHIzlpRZxsVFokjfZC1MeS6FKlE7XtBfrYOofS/Lzkxv4w7EzffXIDvUguhnXpPs3jYaRjA+AVVHHYiDWoG4iiVrSCl9J+SQslkJUQvLz20/5qsMWWhvPqHcKrFBJ95Lp4FfwHfsHEiB+3oydCQXEoraxrKuHOrRolZkyVNi9TcS4rKw8h1i76FLedwB4RVDqnwAz43V3sMDTJUMWwL9inL/HQWKZTxJeFmeY6D537sGXWCjQoAtUEmP4LJZ2b8/mholJFnxVyJma48Oc4UHVa7s/gWVL4v9DCll3rO4Q6Oq9wYvmwnRCLt+oG6guGgu9dECi12uIHV7ciUTatB5Iwp72BU3IPVyz/HzNOEe3lE888Ujn/Cjd+B1IlPsftj5L4yisb1K4m4jqQrCpSZ6XgGVtIcsZkJEUVbhZbuVUdJCO+E/+4Ll8xthxDYcH1mAyuRWe84XgInuJOTyYN3t7zk1HUkSA7eYGOderA2Ato=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
