travis:
  secure:
    BINSTAR_TOKEN: cGO/vNAiLO5YmS/mHbMBJcE69vhGsdpiz6bx92Fp6IsS2zZhVTsBrukv8o5jg+hv83ESJJq/LjYoivWwyBBVaoamFIpnPvwwZysF79MN7B+UXWQAtmgv1RUb1GZgxP2kBb03l9YGfipWGWW+m2o+RDKNLMImR2F9OYQL7+pKSFIQSgB/aNhLPSerscsW+PIUqq0qY2kFZeZvZH82YSjkJThNtEgJzkSO6K5eUtWFIsFN13vtem7hUKT0Ek6x66LLYljM/l5ktBjrrYb6DfNB8GVSc9aEeFYzsCTKGaZSwI1xLcF9uhqviYtI8VLePxSWUEG23HkbbEpjg/2/hrmkToAtBVW5nU3BuJx19saCPJVWtANvHvC4StI+ZgILD/Msf46XI08UjXPvEejU7bHWD2tSUW61/VVtmChKBvtK39sfR2Hgo3xzotVSZ9IdcreOMEh3B9wpM+gu6sfIK8UEXk+iKstiLCjQ5bIOszXOrtC378KO54U491b7TA98kYDMRvd58OaYdA+4JhMQzCznTBHRBtm1/h1/jfydKubbupkY/7+jmp3XzI491b7RM6O4m18xO0epJXswlNamyHfuZmrWaWE0tjmRyEPrDjcxncPaC4ofAZW6Rn+oBbJcX52ZLJeEHKQSXgDHHRYsWUYsTNJttmwofoKsGCwVUUNzxQs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
