travis:
  secure:
    BINSTAR_TOKEN: TWdA+kmCAHZ2sgcnH2CsrtQnIcc4bOXV4k3f05hVFBJex5Qq49ZF4x5kVKxOW/N9dQA+twEfjqId4w2rminAr2KbHGxqqUPP8vVU+tUhnAbocX8y0pdJSGquI4e7uQIYRDErvHU7XHzbUNge8eHMWtNJEBAp3C+WY1yUGcWIbXcqfz0vDcTlXa4UYbgcN+6hJ0JZxqRbGiB78pXqyt0ZPI7j7y8Ey+njWBlGSK5NU3kmw2pyQw889pe81Cmpfo5TDjISbyO5crRfR1Mm9lRV4lCZ9kdP9dg+2xevK5EU4fprM54OV00kyXd0VQiU8fVqmM1IE0zvn/X4ugU1e8CavnZWhRbU3L23TDY7dqUoaL/9qgNMYBTJWYl6Bix6mbLV4YNjdmz8CeOc4p6I2Slt8ljzUUUzAYQJKgL/lIUCL7EnKymOl5tKpj9Yi350BOd3W2IJ6crQmbSDZZkPvrFpBd1sMP9vqrXjzUs6MFU+3VHKVmPswg3Ku6ApMqABEXzgUB0DvcaUKkw5128buc1pQeVK6JC6UnzxrP/3o3YR2KHZ6FywBxWGV5k1yfGRgeewVf+FVaSaF18/b+9DCTlqCg6+vnbBpLUuELkQ7WpElQg2mGKQSVOmXLo44INflwvvA8AApkI9IubwYT4Uxj+GNj0DSVY7liaHzeS5I3DF3kw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
