travis:
  secure:
    BINSTAR_TOKEN: NUW54JGPpmFgxho3Nj1LO+iByfzby6bVDqH49ZwPmbq0PV4dxwV+LBeANqntCT1LGp7/ACpdXDRv/iA+4/6tztqvA3f6usrTIVCuc8Diuyq7w1GueedpTRi2J0FSngRC8ELgX97xeFCPPctg8R8Vk8Yn/32vholZmEFH0yUqpYBBEWaBrEkpIJBmaB53NKS3QEPQZyaPKKmQBHqAUAg6F1eom6QnywdX0VlPCD4KmxDft1/mbC1nh3lcB7rwMFS45sJ190VvsdGERa7osWcpsKN5ke3DgeThScgxYQaq7QKxYRESysisygWzYa/V3KgiVUNDTnrX5QWFZlKFQPoak0brdfTqQvw59GKveYlBiPtp2xGLJjXhWa6rESFoRS0Iv/z/8F96Z+7f1iQAOMLqMCp6hyhLiQEgC+FfLrqtMIAx3n8CMT8xsad4T5s0OXlJ40s0LgfFDdEVdyPMP8DM46Ijnng0wq1zOyWMBFJRS4hjXjNdj3bgzkS5AiOcTI/JThzTEo1YhyBkFPlGsjZH2DA8QxR/gslnrHS8ykfw/xdR1Y4WXJoTjM/BMT/iLasnjNxmXronKDRKRyXMREdd8f6mplbEO0GQePa/YnwUfmiYO6yHoOnpZmAJc/jFBsKhYfjpxzQ6zQaw/gvL6SsVcEE/Facs8QybAExJ2M5rhjs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
